import { test, expect } from "@playwright/test";
import { seedAndEnterGame, tapPlayerByNumber } from "./_helpers";

test("/game/scoresheet shows per-period and final score totals", async ({ page }) => {
  await seedAndEnterGame(page);
  await page.getByRole("button", { name: /Tip Off/ }).click();

  // Period 1: home +3, away +2
  await tapPlayerByNumber(page, "home", "1");
  await page.getByRole("button", { name: /^\+3 Made/ }).click();
  await tapPlayerByNumber(page, "away", "11");
  await page.getByRole("button", { name: /^\+2 Made/ }).click();

  // End P1, start P2 — between Q1 and Q2 the button label is "Start Next Quarter".
  await page.getByRole("button", { name: /End Period/ }).last().click();
  await page.getByRole("button", { name: /Start Next Quarter/ }).click();

  // Period 2: away +3
  await tapPlayerByNumber(page, "away", "11");
  await page.getByRole("button", { name: /^\+3 Made/ }).click();

  await page.getByRole("link", { name: "Scoresheet" }).click();
  await expect(page).toHaveURL(/\/game\/scoresheet$/);

  // The Quarter Scores table renders Final = 3 (home), 5 (away)
  const finalCells = page
    .getByRole("table")
    .first()
    .getByText(/^[0-9]+$/)
    .filter({ hasNotText: /[a-z]/ });
  // Pick the last numeric cell of the home row (FINAL column)
  const homeRow = page.getByRole("row").filter({ has: page.getByText("Home Team") });
  const awayRow = page.getByRole("row").filter({ has: page.getByText("Away Team") });
  await expect(homeRow.locator("td").last()).toHaveText("3");
  await expect(awayRow.locator("td").last()).toHaveText("5");
  expect(await finalCells.count()).toBeGreaterThan(0);
});

test("scoresheet renders signature placeholders and timestamp", async ({ page }) => {
  await seedAndEnterGame(page);
  await page.getByRole("link", { name: "Scoresheet" }).click();
  // Two cells contain the substring "Scorekeeper" (Scorekeeper and Assistant
  // Scorekeeper); just assert at least one exists by exact match.
  await expect(page.getByText("Scorekeeper", { exact: true })).toBeVisible();
  await expect(page.getByText("Crew Chief")).toBeVisible();
  await expect(page.getByText(/Generated by CourtLog/)).toBeVisible();
});
