"use client";

import { useMemo } from "react";
import { useGameStore } from "@/lib/store";
import { computeStats } from "@/lib/stats";
import type { GameEvent, Side, Team } from "@/lib/types";
import { formatPeriod, cn } from "@/lib/utils";
import { POINTS_BY_KIND } from "@/lib/constants";

/**
 * Official-style digital scoresheet. Designed to mirror the layout of a
 * paper FIBA scoresheet so officials recognise the format instantly.
 *
 * Per-period breakdown and cumulative score progression are derived from
 * the event log at render time.
 */
export default function ScoresheetPage() {
  const homeTeam = useGameStore((s) => s.homeTeam);
  const awayTeam = useGameStore((s) => s.awayTeam);
  const settings = useGameStore((s) => s.settings);
  const events = useGameStore((s) => s.events);
  const period = useGameStore((s) => s.currentPeriod);

  const stats = useMemo(
    () => computeStats(events, homeTeam, awayTeam, settings, period),
    [events, homeTeam, awayTeam, settings, period],
  );

  const periodScores = useMemo(
    () => computePeriodScores(events, settings.periods, period),
    [events, settings.periods, period],
  );

  return (
    <div className="panel p-5 md:p-8 overflow-auto scrollbar-thin h-full">
      {/* Header — competition / venue */}
      <div className="border-b-2 border-surface-border pb-4 mb-6">
        <div className="flex items-start justify-between flex-wrap gap-2">
          <div>
            <p className="label-eyebrow">Official Digital Scoresheet</p>
            <h1 className="heading-display text-3xl mt-1">
              {settings.competition || "Untitled Competition"}
            </h1>
            <p className="text-sm text-ink-muted">
              {settings.venue || "Venue not specified"}
            </p>
          </div>
          <div className="text-right">
            <p className="label-eyebrow">Format</p>
            <p className="heading-display text-2xl">{settings.format}</p>
          </div>
        </div>
      </div>

      {/* Period-by-period summary */}
      <section className="mb-6">
        <h2 className="label-eyebrow mb-2">Quarter Scores</h2>
        <div className="overflow-x-auto">
          <table className="w-full min-w-[600px] border-collapse text-sm font-mono tabular">
            <thead>
              <tr className="border-b border-surface-border">
                <th className="text-left py-2 px-3">Team</th>
                {periodScores.home.map((_, i) => (
                  <th key={i} className="py-2 px-3 text-center">
                    {formatPeriod(i + 1, settings.periods)}
                  </th>
                ))}
                <th className="py-2 px-3 text-center text-accent">FINAL</th>
              </tr>
            </thead>
            <tbody>
              <ScoreRow team={homeTeam} scores={periodScores.home} />
              <ScoreRow team={awayTeam} scores={periodScores.away} />
            </tbody>
          </table>
        </div>
      </section>

      {/* Team blocks */}
      <div className="grid lg:grid-cols-2 gap-6">
        <TeamBlock
          team={homeTeam}
          side="home"
          totals={stats.home}
          players={stats.home.players}
        />
        <TeamBlock
          team={awayTeam}
          side="away"
          totals={stats.away}
          players={stats.away.players}
        />
      </div>

      {/* Signatures — placeholder for officials */}
      <section className="mt-10 grid grid-cols-2 md:grid-cols-4 gap-6">
        <Signature label="Scorekeeper" />
        <Signature label="Assistant Scorekeeper" />
        <Signature label="Timekeeper" />
        <Signature label="Crew Chief" />
      </section>

      <p className="mt-8 text-xs text-ink-dim font-mono text-center">
        Generated by CourtLog · {new Date().toLocaleString()}
      </p>
    </div>
  );
}

/* ── Row pieces ─────────────────────────────────────────────────────── */

function ScoreRow({
  team,
  scores,
}: {
  team: Team;
  scores: number[];
}) {
  const total = scores.reduce((a, b) => a + b, 0);
  return (
    <tr className="border-b border-surface-border/40">
      <td className="py-2 px-3 text-ink">
        <span
          className="inline-block w-2 h-2 mr-2 align-middle"
          style={{ background: team.color }}
          aria-hidden
        />
        {team.name}
      </td>
      {scores.map((s, i) => (
        <td key={i} className="py-2 px-3 text-center">
          {s}
        </td>
      ))}
      <td className="py-2 px-3 text-center font-display text-xl text-accent">
        {total}
      </td>
    </tr>
  );
}

function TeamBlock({
  team,
  side,
  totals,
  players,
}: {
  team: Team;
  side: Side;
  totals: { points: number; totalFouls: number; timeoutsTaken: number };
  players: ReturnType<typeof computeStats>["home"]["players"];
}) {
  return (
    <section
      className={cn(
        "border-l-4",
        side === "home" ? "border-home" : "border-away",
      )}
    >
      <header className="pl-4 mb-3">
        <p className="label-eyebrow">{team.tag || side.toUpperCase()}</p>
        <h3 className="heading-display text-2xl">{team.name}</h3>
        <p className="text-xs text-ink-muted mt-0.5">
          Coach: {team.coach || "—"}
        </p>
      </header>
      <div className="pl-4 overflow-x-auto">
        <table className="w-full text-xs font-mono tabular border-collapse">
          <thead>
            <tr className="border-b border-surface-border text-ink-dim">
              <th className="text-left py-1 w-10">#</th>
              <th className="text-left py-1">Player</th>
              <th className="py-1">PTS</th>
              <th className="py-1">FG</th>
              <th className="py-1">3P</th>
              <th className="py-1">FT</th>
              <th className="py-1">R</th>
              <th className="py-1">A</th>
              <th className="py-1">PF</th>
            </tr>
          </thead>
          <tbody>
            {team.roster.map((p) => {
              const line = players.find((s) => s.playerId === p.id);
              if (!line) return null;
              return (
                <tr key={p.id} className="border-b border-surface-border/30">
                  <td className="py-1 text-ink-muted">{p.number}</td>
                  <td className="py-1 truncate max-w-[140px] text-ink">
                    {p.name}
                    {p.isCaptain ? <span className="text-accent ml-1">C</span> : null}
                  </td>
                  <td className="py-1 text-right text-ink">{line.points}</td>
                  <td className="py-1 text-right">
                    {line.fgMade}/{line.fgAttempted}
                  </td>
                  <td className="py-1 text-right">
                    {line.threePtMade}/{line.threePtAttempted}
                  </td>
                  <td className="py-1 text-right">
                    {line.ftMade}/{line.ftAttempted}
                  </td>
                  <td className="py-1 text-right">{line.rebounds}</td>
                  <td className="py-1 text-right">{line.assists}</td>
                  <td className="py-1 text-right">{line.fouls}</td>
                </tr>
              );
            })}
          </tbody>
          <tfoot>
            <tr className="border-t-2 border-surface-border font-medium">
              <td />
              <td className="py-2 uppercase text-ink-muted">Totals</td>
              <td className="py-2 text-right text-accent font-display text-base">
                {totals.points}
              </td>
              <td colSpan={5} />
              <td className="py-2 text-right">{totals.totalFouls}</td>
            </tr>
          </tfoot>
        </table>
      </div>
    </section>
  );
}

function Signature({ label }: { label: string }) {
  return (
    <div>
      <div className="h-10 border-b border-ink-dim/40" aria-hidden />
      <p className="label-eyebrow mt-2">{label}</p>
    </div>
  );
}

/* ── Period aggregation ─────────────────────────────────────────────── */

/**
 * For each period, compute the points each team scored in that period only.
 * This walks the event list once.
 */
function computePeriodScores(
  events: GameEvent[],
  regularPeriods: number,
  currentPeriod: number,
): { home: number[]; away: number[] } {
  // Determine how many period columns to show (regular + any OTs reached)
  const totalPeriods = Math.max(regularPeriods, currentPeriod);
  const home: number[] = new Array(totalPeriods).fill(0);
  const away: number[] = new Array(totalPeriods).fill(0);

  for (const ev of events) {
    if (ev.type !== "score" || !ev.made) continue;
    const idx = ev.period - 1;
    if (idx < 0 || idx >= totalPeriods) continue;
    const points = POINTS_BY_KIND[ev.kind];
    if (ev.side === "home") home[idx]! += points;
    else away[idx]! += points;
  }

  return { home, away };
}
